### ISSUE TITLE
Boquear novas conexões

### ISSUE THREAD

**Issue by lucianovsjr** [totvs/tds-monitor#11]
Criar funcionalidade para bloquear novas conexões no sistema, necessário uso exclusivo para compilar um fonte.

**Comment by tramostrc** [comment]
Olá Luciano, tudo bom

Eu uso o seguinte procedimento para compilar fontes e patches.

Eu tenho o ambiente de Produção [PRODUCAO] e um ambiente de Compilação chamado [COMPILA]
Na pasta APO crio uma pasta com a data de hoje copiando o RPO que está em uso, exemplo: APO/20200702/TTTP120.RPO
Altero o caminho do RPO do ambiente COMPILA para ...APO/20200702
Compilo o que é necessário e posso acessar testar os ajustes
Se ok, é só alterar o caminho do RPO do ambiente de PRODUCAO para o mesmo do COMPILA, para os usuários que estiverem logado aparecerá a mensagem de que houve uma atualização e ao confirmar ele irá carregar o novo RPO.

Além de subir ajustes "à quente" você terá um versionamento de RPO´s na pasta APO.

Uso esse procedimento também para o TSS, reiniciando o TSS após alteração do caminho do RPO de produção.

Espero ter ajudado.

Abraços

Thiago

**Comment by lucianovsjr** [comment]
Ótima ideia @tramostrc, esse procedimento resolve o meu problema.

Muito obrigado pela ajuda.

Abraço.
